"""
================================================================================
LOGIK SYSTEMS EOOD - AI-ASSISTED COMPLIANCE SUPPORT PLATFORM
Location: Vratsa, Bulgaria | UIC: 208569532
Version: 1.0 - Transparent RegTech Infrastructure
================================================================================

DISCLAIMER: This system provides AI-assisted risk assessment for EU AI Act compliance.
It is NOT a substitute for professional legal or compliance advice.
All reports are generated by automated analysis and should be reviewed by qualified professionals.

================================================================================
"""

import os
import time
import hashlib
import stripe
import openai
from datetime import datetime
from fastapi import FastAPI, Request, BackgroundTasks, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv
from supabase import create_client, Client
from typing import Optional

# --- 1. ENVIRONMENT CONFIGURATION ---
load_dotenv()

stripe.api_key = os.getenv("STRIPE_API_KEY")
# OpenAI client will be initialized on demand
client = None
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

supabase_url = os.getenv("SUPABASE_URL")
supabase_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
# Supabase client will be initialized on demand
supabase = None

app = FastAPI(
    title="Logik Systems - Compliance Support Platform",
    description="AI-Assisted EU AI Act Compliance Assessment Tool"
)

# --- 2. CORS CONFIGURATION ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://www.logik-systems.com", "https://logik-systems.com", "http://localhost:3000"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 3. SERVICE TIERS (TRANSPARENT PRICING) ---
TIERS = {
    "audit_scan": {
        "price": "price_1250",
        "price_eur": 1250,
        "label": "AuditScan",
        "description": "Basic AI-assisted risk assessment for single AI system",
        "features": ["Automated compliance checklist", "Risk scoring", "Basic report"]
    },
    "governance_core": {
        "price": "price_4800",
        "price_eur": 4800,
        "label": "GovernanceCore",
        "description": "Comprehensive compliance framework for enterprise AI governance",
        "features": ["Multi-system analysis", "Governance framework", "Quarterly reviews", "Priority support"]
    },
    "sovereign_shield": {
        "price": "price_12500",
        "price_eur": 12500,
        "label": "SovereignShield",
        "description": "Premium compliance monitoring with continuous assessment",
        "features": ["Real-time monitoring", "Incident response", "Compliance dashboard", "Dedicated analyst review"]
    }
}

# --- 4. DATA MODELS ---
class ComplianceAuditRequest(BaseModel):
    """Request model for compliance assessment"""
    system_name: str
    system_description: str
    ai_model_type: str  # e.g., "LLM", "Computer Vision", "Recommendation Engine"
    use_case: str
    data_categories: list[str]
    tier: str

class LinkedInOutreachRequest(BaseModel):
    """Request model for B2B outreach (LinkedIn compliant)"""
    prospect_name: str
    prospect_company: str
    prospect_email: str
    prospect_role: str
    identified_use_case: str
    consent_given: bool  # GDPR compliance

class ComplianceReport(BaseModel):
    """Internal model for compliance reports"""
    audit_id: str
    customer_id: str
    system_name: str
    risk_level: str  # LOW, MEDIUM, HIGH
    compliance_score: float  # 0-100
    findings: list[str]
    recommendations: list[str]
    disclaimer: str
    created_at: str

# --- 5. UTILITY FUNCTIONS ---

def generate_audit_id():
    """Generate unique audit identifier"""
    timestamp = int(time.time() * 1000)
    random_hash = hashlib.sha256(str(timestamp).encode()).hexdigest()[:8]
    return f"AUDIT-{timestamp}-{random_hash.upper()}"

def get_compliance_disclaimer():
    """Standard disclaimer for all reports"""
    return (
        "⚠️ IMPORTANT DISCLAIMER:\n"
        "This report is generated by an AI-assisted analysis system and is NOT a substitute for professional legal or compliance advice.\n"
        "Logik Systems EOOD is a technology provider, not a licensed compliance consultant or law firm.\n"
        "All findings should be reviewed by qualified compliance professionals before implementation.\n"
        "This assessment is based on the information provided and current EU AI Act guidelines as of the analysis date.\n"
        "Logik Systems EOOD assumes no liability for decisions made based solely on this automated analysis."
    )

async def generate_compliance_assessment(request: ComplianceAuditRequest) -> dict:
    """
    Generate AI-assisted compliance assessment
    Uses GPT-4 to analyze against EU AI Act requirements
    """
    prompt = f"""
    You are a compliance assessment assistant for EU AI Act compliance.
    
    IMPORTANT: Your analysis is AI-generated and must be reviewed by qualified professionals.
    
    Analyze the following AI system for EU AI Act compliance:
    
    System Name: {request.system_name}
    Description: {request.system_description}
    Model Type: {request.ai_model_type}
    Use Case: {request.use_case}
    Data Categories: {', '.join(request.data_categories)}
    
    Provide:
    1. Risk Level Assessment (LOW/MEDIUM/HIGH)
    2. Compliance Score (0-100)
    3. Key Findings (list 5-7 specific areas)
    4. Recommendations (list 5-7 actionable steps)
    
    Format as JSON with keys: risk_level, compliance_score, findings, recommendations
    
    Remember: This is an automated analysis tool, not legal advice.
    """
    
    try:
        response = await client.chat.completions.create(
            model="gpt-4-turbo",
            messages=[
                {
                    "role": "system",
                    "content": "You are a compliance assessment tool. Provide structured, honest analysis. Always remind users this is AI-generated and not legal advice."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7,
            max_tokens=1500
        )
        
        return {
            "status": "success",
            "analysis": response.choices[0].message.content
        }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e)
        }

# --- 6. API ENDPOINTS ---

@app.get("/")
async def health_check():
    """Health check endpoint"""
    return {
        "service": "Logik Systems Compliance Support Platform",
        "company": "Logik Systems EOOD",
        "uic": "208569532",
        "status": "operational",
        "version": "1.0",
        "timestamp": datetime.utcnow().isoformat()
    }

@app.get("/compliance/disclaimer")
async def get_disclaimer():
    """Public endpoint for compliance disclaimer"""
    return {
        "disclaimer": get_compliance_disclaimer(),
        "service_type": "AI-Assisted Compliance Support Software",
        "not_legal_advice": True,
        "professional_review_required": True
    }

@app.post("/v1/audit")
async def start_compliance_audit(request: ComplianceAuditRequest):
    """
    Main endpoint: Start a compliance assessment
    
    Returns:
    - Audit ID for tracking
    - Preliminary assessment
    - Disclaimer
    - Next steps
    """
    
    # Validate tier
    if request.tier not in TIERS:
        raise HTTPException(status_code=400, detail=f"Invalid tier. Choose from: {list(TIERS.keys())}")
    
    # Generate audit ID
    audit_id = generate_audit_id()
    
    # Generate assessment
    assessment = await generate_compliance_assessment(request)
    
    if assessment["status"] != "success":
        raise HTTPException(status_code=500, detail="Assessment generation failed")
    
    # Create audit record in Supabase
    audit_record = {
        "audit_id": audit_id,
        "system_name": request.system_name,
        "tier": request.tier,
        "status": "completed",
        "assessment": assessment["analysis"],
        "disclaimer": get_compliance_disclaimer(),
        "created_at": datetime.utcnow().isoformat()
    }
    
    try:
        supabase.table("audits").insert(audit_record).execute()
    except Exception as e:
        print(f"Database error: {str(e)}")
        # Continue even if DB fails - return assessment
    
    return {
        "audit_id": audit_id,
        "tier": request.tier,
        "service_tier_info": TIERS[request.tier],
        "assessment": assessment["analysis"],
        "disclaimer": get_compliance_disclaimer(),
        "next_steps": [
            "1. Review this automated assessment with your compliance team",
            "2. Engage qualified professionals for detailed legal review",
            "3. Implement recommended changes",
            "4. Schedule follow-up assessment"
        ],
        "support_contact": "support@logik-systems.com"
    }

@app.post("/v1/linkedin/outreach")
async def send_linkedin_outreach(request: LinkedInOutreachRequest):
    """
    B2B Outreach endpoint (LinkedIn compliant)
    
    COMPLIANCE NOTES:
    - Respects LinkedIn automation policies
    - Requires explicit consent
    - Clearly identifies as automated outreach
    - Includes opt-out mechanism
    """
    
    # Validate consent
    if not request.consent_given:
        raise HTTPException(status_code=400, detail="Consent required for outreach")
    
    # Generate outreach record
    outreach_id = f"OUTREACH-{int(time.time())}-{hashlib.md5(request.prospect_email.encode()).hexdigest()[:8].upper()}"
    
    # Create personalized message (transparent about automation)
    message = f"""
    Hi {request.prospect_name},
    
    This is an automated outreach from Logik Systems EOOD.
    
    We identified that {request.prospect_company} may benefit from AI compliance assessment, particularly for: {request.identified_use_case}
    
    Our platform provides AI-assisted compliance support for EU AI Act requirements. We're not a law firm, but we help teams understand their compliance landscape.
    
    Would you be open to a brief conversation about your current AI governance approach?
    
    Best regards,
    Logik Systems Team
    
    ---
    This is an automated message. To opt-out, reply with "STOP".
    """
    
    # Store outreach record
    outreach_record = {
        "outreach_id": outreach_id,
        "prospect_name": request.prospect_name,
        "prospect_company": request.prospect_company,
        "prospect_email": request.prospect_email,
        "prospect_role": request.prospect_role,
        "use_case": request.identified_use_case,
        "message": message,
        "status": "pending",
        "created_at": datetime.utcnow().isoformat()
    }
    
    try:
        supabase.table("outreach_log").insert(outreach_record).execute()
    except Exception as e:
        print(f"Outreach logging error: {str(e)}")
    
    return {
        "outreach_id": outreach_id,
        "status": "queued",
        "prospect": request.prospect_name,
        "company": request.prospect_company,
        "message_preview": message[:200] + "...",
        "compliance_notes": [
            "✓ Clearly identified as automated outreach",
            "✓ Includes opt-out mechanism",
            "✓ Transparent about service type",
            "✓ No false claims about legal authority"
        ]
    }

@app.post("/webhook")
async def stripe_webhook(request: Request, sig_header: str = Header(None)):
    """
    Stripe webhook handler for payment events
    """
    payload = await request.body()
    
    try:
        event = stripe.Webhook.construct_event(
            payload,
            sig_header,
            STRIPE_WEBHOOK_SECRET
        )
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid payload")
    except stripe.error.SignatureVerificationError:
        raise HTTPException(status_code=400, detail="Invalid signature")
    
    # Handle payment success
    if event['type'] == 'invoice.payment_succeeded':
        invoice = event['data']['object']
        print(f"[✓] Payment received: {invoice['id']} - Amount: {invoice['amount_paid']/100} EUR")
        
        # Log to database
        try:
            supabase.table("payments").insert({
                "stripe_invoice_id": invoice['id'],
                "amount_eur": invoice['amount_paid'] / 100,
                "status": "completed",
                "created_at": datetime.utcnow().isoformat()
            }).execute()
        except Exception as e:
            print(f"Payment logging error: {str(e)}")
    
    return {"status": "success"}

@app.get("/mcp")
async def mcp_discovery():
    """
    MCP (Model Context Protocol) discovery endpoint
    Allows integration with Kortix and other AI systems
    """
    return {
        "mcp_version": "1.0",
        "service": "Logik Systems Compliance Support",
        "capabilities": {
            "tools": [
                {
                    "name": "get_compliance_status",
                    "description": "Retrieve compliance assessment status for an audit"
                },
                {
                    "name": "list_audits",
                    "description": "List all compliance audits for a customer"
                }
            ],
            "resources": [
                {
                    "uri": "mcp://compliance/audits",
                    "name": "Compliance Audit History"
                },
                {
                    "uri": "mcp://compliance/disclaimer",
                    "name": "Service Disclaimer"
                }
            ]
        },
        "transparency": "All assessments are AI-generated and require professional review"
    }

@app.get("/mcp/compliance/audits")
async def mcp_get_audits(limit: int = 10):
    """MCP resource: Get recent audits"""
    try:
        response = supabase.table("audits").select("*").limit(limit).execute()
        return {
            "audits": response.data,
            "count": len(response.data),
            "disclaimer": "These are AI-generated assessments. Professional review required."
        }
    except Exception as e:
        return {"error": str(e), "audits": []}

# --- 7. ERROR HANDLERS ---

@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return {
        "error": exc.detail,
        "status_code": exc.status_code,
        "timestamp": datetime.utcnow().isoformat()
    }

# --- 8. STARTUP ---

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
